let data = {
  Aphelios: ["ADC"],
  Ashe: ["ADC", "SUPPORT"],
  Caitlyn: ["ADC"],
  Cassiopeia: ["ADC", "MID", "TOP"],
  Draven: ["ADC"],
  Ezreal: ["ADC"],
  Heimerdinger: ["ADC", "MID", "TOP"],
  Jhin: ["ADC"],
  Jinx: ["ADC"],
  "Kai'Sa": ["ADC", "MID"],
  Kalista: ["ADC"],
  Karthus: ["ADC", "JUNGLE", "MID"],
  "Kog'Maw": ["ADC", "MID"],
  Lucian: ["ADC", "MID"],
  "Miss Fortune": ["ADC"],
  Samira: ["ADC"],
  Seraphine: ["ADC", "MID", "SUPPORT"],
  Sivir: ["ADC"],
  Swain: ["ADC", "MID", "SUPPORT"],
  Tristana: ["ADC", "MID"],
  Twitch: ["ADC"],
  Varus: ["ADC"],
  Vayne: ["ADC", "TOP"],
  Veigar: ["ADC", "MID"],
  Xayah: ["ADC"],
  Yasuo: ["ADC", "MID", "TOP"],
  Zeri: ["ADC"],
  Ziggs: ["ADC", "MID"],
  Amumu: ["JUNGLE", "SUPPORT"],
  Diana: ["JUNGLE", "MID"],
  Ekko: ["JUNGLE", "MID"],
  Elise: ["JUNGLE"],
  Evelynn: ["JUNGLE"],
  Fiddlesticks: ["JUNGLE"],
  Gragas: ["JUNGLE", "SUPPORT", "TOP"],
  Graves: ["JUNGLE", "TOP"],
  Gwen: ["JUNGLE", "TOP"],
  Hecarim: ["JUNGLE"],
  Ivern: ["JUNGLE"],
  "Jarvan IV": ["JUNGLE"],
  Jax: ["JUNGLE", "TOP"],
  Kayn: ["JUNGLE"],
  "Kha'Zix": ["JUNGLE"],
  Kindred: ["JUNGLE"],
  "Lee Sin": ["JUNGLE"],
  Lillia: ["JUNGLE", "TOP"],
  "Master Yi": ["JUNGLE"],
  Mordekaiser: ["JUNGLE", "TOP"],
  Nidalee: ["JUNGLE"],
  Nocturne: ["JUNGLE"],
  "Nunu & Willump": ["JUNGLE"],
  Olaf: ["JUNGLE", "TOP"],
  Poppy: ["JUNGLE", "TOP"],
  Qiyana: ["JUNGLE", "MID"],
  Rammus: ["JUNGLE"],
  "Rek'Sai": ["JUNGLE"],
  Rengar: ["JUNGLE", "TOP"],
  Rumble: ["JUNGLE", "MID", "TOP"],
  Sejuani: ["JUNGLE", "TOP"],
  Shaco: ["JUNGLE", "SUPPORT"],
  Shyvana: ["JUNGLE", "TOP"],
  Skarner: ["JUNGLE", "TOP"],
  Taliyah: ["JUNGLE", "MID", "SUPPORT"],
  Talon: ["JUNGLE", "MID"],
  Trundle: ["JUNGLE", "TOP"],
  Udyr: ["JUNGLE"],
  Vi: ["JUNGLE"],
  Viego: ["JUNGLE"],
  Volibear: ["JUNGLE", "TOP"],
  Warwick: ["JUNGLE", "TOP"],
  Wukong: ["JUNGLE", "TOP"],
  "Xin Zhao": ["JUNGLE"],
  Zac: ["JUNGLE"],
  Zed: ["JUNGLE", "MID"],
  Ahri: ["MID"],
  Akali: ["MID", "TOP"],
  Akshan: ["MID", "TOP"],
  Anivia: ["MID", "SUPPORT"],
  Annie: ["MID"],
  "Aurelion Sol": ["MID"],
  Azir: ["MID"],
  Brand: ["MID", "SUPPORT"],
  "Cho'Gath": ["MID", "TOP"],
  Corki: ["MID"],
  Fizz: ["MID"],
  Galio: ["MID", "SUPPORT"],
  Gangplank: ["MID", "TOP"],
  Irelia: ["MID", "TOP"],
  Jayce: ["MID", "TOP"],
  Karma: ["MID", "SUPPORT"],
  Kassadin: ["MID"],
  Katarina: ["MID"],
  Kayle: ["MID", "TOP"],
  Kennen: ["MID", "TOP"],
  Kled: ["MID", "TOP"],
  LeBlanc: ["MID"],
  Lissandra: ["MID"],
  Lux: ["MID", "SUPPORT"],
  Malphite: ["MID", "SUPPORT", "TOP"],
  Malzahar: ["MID"],
  Neeko: ["MID", "SUPPORT"],
  Orianna: ["MID"],
  Pantheon: ["MID", "SUPPORT", "TOP"],
  Renekton: ["MID", "TOP"],
  Ryze: ["MID", "TOP"],
  Singed: ["MID", "TOP"],
  Sylas: ["MID", "TOP"],
  Syndra: ["MID"],
  "Twisted Fate": ["MID"],
  "Vel'Koz": ["MID", "SUPPORT"],
  Vex: ["MID"],
  Viktor: ["MID"],
  Vladimir: ["MID", "TOP"],
  Xerath: ["MID", "SUPPORT"],
  Yone: ["MID", "TOP"],
  Zilean: ["MID", "SUPPORT"],
  Zoe: ["MID"],
  Alistar: ["SUPPORT"],
  Bard: ["SUPPORT"],
  Blitzcrank: ["SUPPORT"],
  Braum: ["SUPPORT"],
  Janna: ["SUPPORT"],
  Leona: ["SUPPORT"],
  Lulu: ["SUPPORT"],
  Maokai: ["SUPPORT", "TOP"],
  Morgana: ["SUPPORT"],
  Nami: ["SUPPORT"],
  Nautilus: ["SUPPORT"],
  Pyke: ["SUPPORT"],
  Rakan: ["SUPPORT"],
  Rell: ["SUPPORT"],
  "Renata Glasc": ["SUPPORT"],
  Senna: ["SUPPORT"],
  Sett: ["SUPPORT", "TOP"],
  Sona: ["SUPPORT"],
  Soraka: ["SUPPORT"],
  "Tahm Kench": ["SUPPORT", "TOP"],
  Taric: ["SUPPORT"],
  Thresh: ["SUPPORT"],
  Yuumi: ["SUPPORT"],
  Zyra: ["SUPPORT"],
  Aatrox: ["TOP"],
  Camille: ["TOP"],
  Darius: ["TOP"],
  "Dr. Mundo": ["TOP"],
  Fiora: ["TOP"],
  Garen: ["TOP"],
  Gnar: ["TOP"],
  Illaoi: ["TOP"],
  Nasus: ["TOP"],
  Ornn: ["TOP"],
  Quinn: ["TOP"],
  Riven: ["TOP"],
  Shen: ["TOP"],
  Sion: ["TOP"],
  Teemo: ["TOP"],
  Tryndamere: ["TOP"],
  Urgot: ["TOP"],
  Yorick: ["TOP"],
};

export default data